version: 2.1

orbs:
  coveralls: coveralls/coveralls@2.2.1

jobs:
  run_tests_job:
    working_directory: ~/clj-net-pcap
    machine:
      image: ubuntu-2204:2023.10.1
      # https://circleci.com/developer/machine/image/ubuntu-2204
    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            - v1-dependencies-
      - run: sudo apt-get update; sudo apt-get install libpcap0.8 -qq
      - run: sudo ln -s /usr/lib/x86_64-linux-gnu/libpcap.so.0.8 /usr/lib/x86_64-linux-gnu/libpcap.so
      - run: sudo LEIN_ROOT=1 .circleci/bin/lein deps
      - save_cache:
          paths:
            - $HOME/.m2
            - $HOME/.lein
          key: v1-dependencies-{{ checksum "project.clj" }}
      - run: sudo LEIN_ROOT=1 .circleci/bin/lein test
      - run: sudo LEIN_ROOT=1 .circleci/bin/lein cloverage -o cov --coveralls
      - coveralls/upload

workflows:
  run_tests:
    jobs:
      - run_tests_job

