/*
 * Copyright (C) 2005, 2006, 2007, 2008, 2009, 2010 Sly Technologies, Inc.
 *
 * This file is part of jNetPcap.
 *
 * jNetPcap is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as 
 * published by the Free Software Foundation, either version 3 of 
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.jnetpcap.util;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import java.util.List;
import java.util.ListIterator;
import java.util.RandomAccess;

import org.jnetpcap.packet.PcapPacket;
import org.jnetpcap.packet.PcapPacketHandler;

// TODO: Auto-generated Javadoc
/**
 * The Class PcapPacketArrayList.
 * 
 * @author Mark Bednarczyk
 * @author Sly Technologies, Inc.
 */
public class PcapPacketArrayList implements List<PcapPacket>, RandomAccess,
		Serializable, PcapPacketHandler<Object> {

	/** Autogenerated. */
	private static final long serialVersionUID = -6379668946303974430L;

	/** The list. */
	private final ArrayList<PcapPacket> list;

	/**
	 * Instantiates a new pcap packet array list.
	 */
	public PcapPacketArrayList() {
		list = new ArrayList<PcapPacket>();
	}

	/**
	 * Instantiates a new pcap packet array list.
	 * 
	 * @param initialCapacity
	 *          the initial capacity
	 */
	public PcapPacketArrayList(int initialCapacity) {
		list = new ArrayList<PcapPacket>(initialCapacity);
	}

	/**
	 * Instantiates a new pcap packet array list.
	 * 
	 * @param collection
	 *          the collection
	 */
	public PcapPacketArrayList(Collection<? extends PcapPacket> collection) {
		list = new ArrayList<PcapPacket>(collection);
	}

	/**
	 * Adds the.
	 * 
	 * @param index
	 *          the index
	 * @param element
	 *          the element
	 * @see java.util.ArrayList#add(int, java.lang.Object)
	 */
	public void add(int index, PcapPacket element) {
		this.list.add(index, element);
	}

	/**
	 * Adds the.
	 * 
	 * @param o
	 *          the o
	 * @return true, if successful
	 * @see java.util.ArrayList#add(java.lang.Object)
	 */
	public boolean add(PcapPacket o) {
		return this.list.add(o);
	}

	/**
	 * Adds the all.
	 * 
	 * @param c
	 *          the c
	 * @return true, if successful
	 * @see java.util.ArrayList#addAll(java.util.Collection)
	 */
	public boolean addAll(Collection<? extends PcapPacket> c) {
		return this.list.addAll(c);
	}

	/**
	 * Adds the all.
	 * 
	 * @param index
	 *          the index
	 * @param c
	 *          the c
	 * @return true, if successful
	 * @see java.util.ArrayList#addAll(int, java.util.Collection)
	 */
	public boolean addAll(int index, Collection<? extends PcapPacket> c) {
		return this.list.addAll(index, c);
	}

	/**
	 * Clear.
	 * 
	 * @see java.util.ArrayList#clear()
	 */
	public void clear() {
		this.list.clear();
	}

	/**
	 * Clone.
	 * 
	 * @return the object
	 * @see java.util.ArrayList#clone()
	 */
	@Override
	public Object clone() {
		return this.list.clone();
	}

	/**
	 * Contains.
	 * 
	 * @param elem
	 *          the elem
	 * @return true, if successful
	 * @see java.util.ArrayList#contains(java.lang.Object)
	 */
	public boolean contains(Object elem) {
		return this.list.contains(elem);
	}

	/**
	 * Contains all.
	 * 
	 * @param c
	 *          the c
	 * @return true, if successful
	 * @see java.util.AbstractCollection#containsAll(java.util.Collection)
	 */
	public boolean containsAll(Collection<?> c) {
		return this.list.containsAll(c);
	}

	/**
	 * Ensure capacity.
	 * 
	 * @param minCapacity
	 *          the min capacity
	 * @see java.util.ArrayList#ensureCapacity(int)
	 */
	public void ensureCapacity(int minCapacity) {
		this.list.ensureCapacity(minCapacity);
	}

	/**
	 * Equals.
	 * 
	 * @param o
	 *          the o
	 * @return true, if successful
	 * @see java.util.AbstractList#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		return this.list.equals(o);
	}

	/**
	 * Gets the.
	 * 
	 * @param index
	 *          the index
	 * @return the pcap packet
	 * @see java.util.ArrayList#get(int)
	 */
	public PcapPacket get(int index) {
		return this.list.get(index);
	}

	/**
	 * Hash code.
	 * 
	 * @return the int
	 * @see java.util.AbstractList#hashCode()
	 */
	@Override
	public int hashCode() {
		return this.list.hashCode();
	}

	/**
	 * Index of.
	 * 
	 * @param elem
	 *          the elem
	 * @return the int
	 * @see java.util.ArrayList#indexOf(java.lang.Object)
	 */
	public int indexOf(Object elem) {
		return this.list.indexOf(elem);
	}

	/**
	 * Checks if is empty.
	 * 
	 * @return true, if is empty
	 * @see java.util.ArrayList#isEmpty()
	 */
	public boolean isEmpty() {
		return this.list.isEmpty();
	}

	/**
	 * Iterator.
	 * 
	 * @return the iterator
	 * @see java.util.AbstractList#iterator()
	 */
	public Iterator<PcapPacket> iterator() {
		return this.list.iterator();
	}

	/**
	 * Last index of.
	 * 
	 * @param elem
	 *          the elem
	 * @return the int
	 * @see java.util.ArrayList#lastIndexOf(java.lang.Object)
	 */
	public int lastIndexOf(Object elem) {
		return this.list.lastIndexOf(elem);
	}

	/**
	 * List iterator.
	 * 
	 * @return the list iterator
	 * @see java.util.AbstractList#listIterator()
	 */
	public ListIterator<PcapPacket> listIterator() {
		return this.list.listIterator();
	}

	/**
	 * List iterator.
	 * 
	 * @param index
	 *          the index
	 * @return the list iterator
	 * @see java.util.AbstractList#listIterator(int)
	 */
	public ListIterator<PcapPacket> listIterator(int index) {
		return this.list.listIterator(index);
	}

	/**
	 * Removes the.
	 * 
	 * @param index
	 *          the index
	 * @return the pcap packet
	 * @see java.util.ArrayList#remove(int)
	 */
	public PcapPacket remove(int index) {
		return this.list.remove(index);
	}

	/**
	 * Removes the.
	 * 
	 * @param o
	 *          the o
	 * @return true, if successful
	 * @see java.util.ArrayList#remove(java.lang.Object)
	 */
	public boolean remove(Object o) {
		return this.list.remove(o);
	}

	/**
	 * Removes the all.
	 * 
	 * @param c
	 *          the c
	 * @return true, if successful
	 * @see java.util.AbstractCollection#removeAll(java.util.Collection)
	 */
	public boolean removeAll(Collection<?> c) {
		return this.list.removeAll(c);
	}

	/**
	 * Retain all.
	 * 
	 * @param c
	 *          the c
	 * @return true, if successful
	 * @see java.util.AbstractCollection#retainAll(java.util.Collection)
	 */
	public boolean retainAll(Collection<?> c) {
		return this.list.retainAll(c);
	}

	/**
	 * Sets the.
	 * 
	 * @param index
	 *          the index
	 * @param element
	 *          the element
	 * @return the pcap packet
	 * @see java.util.ArrayList#set(int, java.lang.Object)
	 */
	public PcapPacket set(int index, PcapPacket element) {
		return this.list.set(index, element);
	}

	/**
	 * Size.
	 * 
	 * @return the int
	 * @see java.util.ArrayList#size()
	 */
	public int size() {
		return this.list.size();
	}

	/**
	 * Sub list.
	 * 
	 * @param fromIndex
	 *          the from index
	 * @param toIndex
	 *          the to index
	 * @return the list
	 * @see java.util.AbstractList#subList(int, int)
	 */
	public List<PcapPacket> subList(int fromIndex, int toIndex) {
		return this.list.subList(fromIndex, toIndex);
	}

	/**
	 * To array.
	 * 
	 * @return the object[]
	 * @see java.util.ArrayList#toArray()
	 */
	public Object[] toArray() {
		return this.list.toArray();
	}

	/**
	 * To array.
	 * 
	 * @param <T>
	 *          the generic type
	 * @param a
	 *          the a
	 * @return the t[]
	 * @see java.util.ArrayList#toArray(Object[])
	 */
	public <T> T[] toArray(T[] a) {
		return this.list.toArray(a);
	}

	/**
	 * To string.
	 * 
	 * @return the string
	 * @see java.util.AbstractCollection#toString()
	 */
	@Override
	public String toString() {
		return this.list.toString();
	}

	/**
	 * Trim to size.
	 * 
	 * @see java.util.ArrayList#trimToSize()
	 */
	public void trimToSize() {
		this.list.trimToSize();
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * org.jnetpcap.packet.PcapPacketHandler#nextPacket(org.jnetpcap.packet.PcapPacket
	 * , java.lang.Object)
	 */
	/**
	 * Next packet.
	 * 
	 * @param packet
	 *          the packet
	 * @param user
	 *          the user
	 * @see org.jnetpcap.packet.PcapPacketHandler#nextPacket(org.jnetpcap.packet.PcapPacket,
	 *      java.lang.Object)
	 */
	public void nextPacket(PcapPacket packet, Object user) {
		list.add(packet);
	}
}
